[global]
# Disable telemetry
gatherUsageStats = false

[server]
# Security settings
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 10

[browser]
# Disable automatic browser opening in production
gatherUsageStats = false

[theme]
# Optional: Custom theme
primaryColor = "#1DB954"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
