# Streamlit Cloud Secrets Configuration
# This file is used for deployment on Streamlit Cloud
# Add your actual secrets in the Streamlit Cloud dashboard

[secrets]
SPOTIFY_CLIENT_ID = "your_spotify_client_id_here"
SPOTIFY_CLIENT_SECRET = "your_spotify_client_secret_here"
SPOTIFY_REDIRECT_URI = "http://localhost:8080/callback"
OPENAI_API_KEY = "your_openai_api_key_here"

# Optional: Add any other configuration
[config]
MAX_REQUESTS_PER_HOUR = 3
RATE_LIMIT_WINDOW_MINUTES = 60
